In [5]:
n=6
n_list =list("0"*n)
n_list[1]="X"
n_list

"X" in n_list

True

In [41]:
abc=np.array(['O','O', 'O', 'O', 'O', 'O', 'X', 'O'])
print(np.where(abc=="O"))
print("abc",abc)
now =2
where_idx = np.where(abc[now+1:]=="O")[0]
print(where_idx)
print(where_idx+now+1)

where_idx2 = np.where(abc[now+1:]=="O")[0]+now+1
print(where_idx2)

(array([0, 1, 2, 3, 4, 5, 7], dtype=int64),)
abc ['O' 'O' 'O' 'O' 'O' 'O' 'X' 'O']
[0 1 2 4]
[3 4 5 7]
[3 4 5 7]


cmd를 최적화해보자

최적화부분만 보자

In [9]:
#CMD 최적화 - 직전에 유형이 같은것이 나온다면 합친다
cmd = ["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]
final_cmd = []
type_dict = {"U":"move","D":"move", "Z":"delete","C":"delete","N":"default"}

#U,D 합치기
move_cmd = []
before_i="N"
for i in cmd:
    if type_dict[i[0]]==type_dict[before_i[0]]:
        if type_dict[i[0]]=="move":
            move_cmd.append(i)

    else:
        if len(move_cmd)>1:
            move_cmd_merged = [ x.replace("U ","-").replace("D ","+") for x in move_cmd]
            res = eval(''.join(move_cmd_merged))
            if res==0:
                pass
            elif res<0:
                cmd = "U "+str(-res)
            elif res>0:
                cmd = "D "+str(res)

            final_cmd.append(cmd)
        elif len(move_cmd)==1:
            final_cmd.append(move_cmd[0])
        else:
            final_cmd.append(i)
    before_i = i

print(final_cmd)

['D 2', 'C', 'U 3', 'C', 'D 4', 'C', 'U 2', 'Z']


최적화했으나, 런타임에러가 부분뜸

In [11]:
import numpy as np
def solution(n, k, cmd):
    nlist =np.array(list("O"*n))
    now_point = k
    deleted_idx = []
    before_nlist = []
    
     
    final_cmd = []
    type_dict = {"U":"move","D":"move", "Z":"delete","C":"delete","N":"default"}

    #U,D 합치기
    move_cmd = []
    before_i="N"
    for i in cmd:
        if type_dict[i[0]]==type_dict[before_i[0]]:
            if type_dict[i[0]]=="move":
                move_cmd.append(i)

        else:
            if len(move_cmd)>1:
                move_cmd_merged = [ x.replace("U ","-").replace("D ","+") for x in move_cmd]
                res = eval(''.join(move_cmd_merged))
                if res==0:
                    pass
                elif res<0:
                    cmd = "U "+str(-res)
                elif res>0:
                    cmd = "D "+str(res)

                final_cmd.append(cmd)
            elif len(move_cmd)==1:
                final_cmd.append(move_cmd[0])
            else:
                final_cmd.append(i)
        before_i = i
    
    for cmd_i in cmd:
        func = cmd_i.split()
        
        #Type1 : Z
        if func[0]=="Z":
            nlist[deleted_idx.pop()]="O"
    
        #TYpe2: C, U, D
        before_nlist = nlist.copy()
        if func[0]=="C":
            nlist[now_point]="X"
            deleted_idx.append(now_point)
            
            temp = np.where(nlist[now_point+1:]=="O")[0]+now_point+1
            if len(temp)==0:
                temp = np.where(nlist[:now_point]=="O")[0]
                now_point = temp[-1]
            else:
                now_point = temp[0]

                
        elif func[0]=="U":
            temp = np.where(nlist[:now_point]=="O")[0]
            now_point = temp[-int(func[1])]
            
        elif func[0]=="D":
            temp = np.where(nlist[now_point+1:]=="O")[0]+now_point+1
            now_point = temp[int(func[1])-1]
    return "".join(nlist)


solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]) #"OOOOXOOO"
# solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z","U 1","C"]) #"OOXOXOOO"                  

'OOOOXOOO'

In [72]:
import numpy as np
def solution(n, k, cmd):
    
    #CMD 최적화 - 직전에 유형이 같은것이 나온다면 합친다
    final_cmd = []
    type_dict = {"U":"move","D":"move", "Z":"delete","C":"delete","N":"default"}

    #U,D 합치기
    move_cmd = []
    before_i="N"
    for i in cmd:
        if type_dict[i[0]]==type_dict[before_i[0]]:
            if type_dict[i[0]]=="move":
                move_cmd.append(i)

        else:
            if len(move_cmd)>1:
                move_cmd_merged = [ x.replace("U ","-").replace("D ","+") for x in move_cmd]
                res = eval(''.join(move_cmd_merged))
                if res==0:
                    pass
                elif res<0:
                    cmd = "U "+str(-res)
                elif res>0:
                    cmd = "D "+str(res)

                final_cmd.append(cmd)
            elif len(move_cmd)==1:
                final_cmd.append(move_cmd[0])
            else:
                pass
        before_i = i
    
    
    nlist =list(range(n))    
    now_point = k
    before_nlist =[]
    
    for cmd_i in final_cmd:
        func = cmd_i.split()
        
        #Type1 : Z
        if func[0]=="Z":
            nlist=before_nlist.pop()
    
        #TYpe2: C, U, D
        
        if func[0]=="C":
            before_nlist.append(nlist.copy())
            nlist.pop(now_point)
            if now_point ==len(nlist)-1:
                now_point-=1
            else:
                now_point+1
                
        elif func[0]=="U":
            now_point-=int(func[1])
            
        elif func[0]=="D":
            now_point+=int(func[1])

    nlist_final = list("X"*n)
    print(nlist)
    for k in nlist:
         nlist_final[k]="O"
                
    return "".join(nlist_final)

solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]) #"OOOOXOOO"
# solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z","U 1","C"]) #"OOXOXOOO"                  


[0, 1, 2, 3, 4, 5, 6, 7]


'OOOOOOOO'

In [ ]:

리스트를 인덱싱 하지않고 바로 delete하게 했으나 그래도 시간초과가 난다 

In [60]:
import numpy as np
def solution(n, k, cmd):
    nlist =list(range(n))    
    now_point = k
    before_nlist =[]
    
    for cmd_i in cmd:
        func = cmd_i.split()
        
        #Type1 : Z
        if func[0]=="Z":
            nlist=before_nlist.pop()
    
        #TYpe2: C, U, D
        
        if func[0]=="C":
            before_nlist.append(nlist.copy())
            nlist.pop(now_point)
            if now_point ==len(nlist)-1:
                now_point-=1
            else:
                now_point+1
                
        elif func[0]=="U":
            now_point-=int(func[1])
            
        elif func[0]=="D":
            now_point+=int(func[1])

        nlist_final = list("X"*n)
#         print(nlist)
        for k in nlist:
             nlist_final[k]="O"
                
    return "".join(nlist_final)


solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]) #"OOOOXOOO"
# solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z","U 1","C"]) #"OOXOXOOO"                  

'OOOOXOOO'

np.where 로바꿨으나 역시 시간초과

In [52]:
import numpy as np
def solution(n, k, cmd):
    nlist =np.array(list("O"*n))
    now_point = k
    deleted_idx = []
    before_nlist = []
    
    for cmd_i in cmd:
        func = cmd_i.split()
        
        #Type1 : Z
        if func[0]=="Z":
            nlist[deleted_idx.pop()]="O"
    
        #TYpe2: C, U, D
        before_nlist = nlist.copy()
        if func[0]=="C":
            nlist[now_point]="X"
            deleted_idx.append(now_point)
            
            temp = np.where(nlist[now_point+1:]=="O")[0]+now_point+1
            if len(temp)==0:
                temp = np.where(nlist[:now_point]=="O")[0]
                now_point = temp[-1]
            else:
                now_point = temp[0]

                
        elif func[0]=="U":
            temp = np.where(nlist[:now_point]=="O")[0]
            now_point = temp[-int(func[1])]
            
        elif func[0]=="D":
            temp = np.where(nlist[now_point+1:]=="O")[0]+now_point+1
            now_point = temp[int(func[1])-1]
    return "".join(nlist)


# solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]) #"OOOOXOOO"
solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z","U 1","C"]) #"OOXOXOOO"                  

'OOXOXOOO'

In [51]:
import numpy as np
def solution(n, k, cmd):
    nlist =np.array(list("O"*n))
    now_point = k
    deleted_idx = []
    before_nlist = []
    
    for cmd_i in cmd:
        print("명령어:",cmd_i)
        func = cmd_i.split()
        
        #Type1 : Z
        if func[0]=="Z":
            nlist[deleted_idx.pop()]="O"
    
        #TYpe2: C, U, D
        before_nlist = nlist.copy()
        if func[0]=="C":
            nlist[now_point]="X"
            deleted_idx.append(now_point)
            
            temp = np.where(nlist[now_point+1:]=="O")[0]+now_point+1
            if len(temp)==0:
                temp = np.where(nlist[:now_point]=="O")[0]
                now_point = temp[-1]
            else:
                now_point = temp[0]

                
        elif func[0]=="U":
            temp = np.where(nlist[:now_point]=="O")[0]
            now_point = temp[-int(func[1])]
            
        elif func[0]=="D":
            temp = np.where(nlist[now_point+1:]=="O")[0]+now_point+1
            print("temp",temp)
            print(func[1])
            now_point = temp[int(func[1])-1]
        
        print("한단계 후 상황:",nlist)
        print("now_point",now_point)
    return "".join(nlist)


# solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]) #"OOOOXOOO"
solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z","U 1","C"]) #"OOXOXOOO"                  

명령어: D 2
temp [3 4 5 6 7]
2
한단계 후 상황: ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
now_point 4
명령어: C
한단계 후 상황: ['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 5
명령어: U 3
한단계 후 상황: ['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 1
명령어: C
한단계 후 상황: ['O' 'X' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 2
명령어: D 4
temp [3 5 6 7]
4
한단계 후 상황: ['O' 'X' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 7
명령어: C
한단계 후 상황: ['O' 'X' 'O' 'O' 'X' 'O' 'O' 'X']
now_point 6
명령어: U 2
한단계 후 상황: ['O' 'X' 'O' 'O' 'X' 'O' 'O' 'X']
now_point 3
명령어: Z
한단계 후 상황: ['O' 'X' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 3
명령어: Z
한단계 후 상황: ['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 3
명령어: U 1
한단계 후 상황: ['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 2
명령어: C
한단계 후 상황: ['O' 'O' 'X' 'O' 'X' 'O' 'O' 'O']
now_point 3


'OOXOXOOO'

다 통과했으나 시간초과남!

In [26]:
import numpy as np
def solution(n, k, cmd):
    nlist =np.array(list("O"*n))
    now_point = k
    deleted_idx = []
    before_nlist = []
    for cmd_i in cmd:
        
        func = cmd_i.split()
        print("now_point",now_point)
        print("어떤 명령어?:",func)
        
        #Type1 : Z
        if func[0]=="Z":
            nlist[deleted_idx.pop()]="O"
    
        #TYpe2: C, U, D
        before_nlist = nlist.copy()
        if func[0]=="C":
            nlist[now_point]="X"
            deleted_idx.append(now_point)
            
            if "O" not in nlist[now_point:]:
                now_point-=1
                while nlist[now_point]=="X":
                    now_point-=1
            else:
                now_point+=1
                while nlist[now_point]=="X":
                    now_point+=1
                
        elif func[0]=="U":
            for k in range(int(func[1])):
                now_point-=1
                if nlist[now_point]!="O":
                    while nlist[now_point]=="X":
                        now_point-=1
            
        elif func[0]=="D":
            for k in range(int(func[1])):
                now_point+=1
                if nlist[now_point]!="O":
                    while nlist[now_point]=="X":
                        now_point+=1
        print(nlist)
        print("now_point",now_point)
    return "".join(nlist)


# solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z"]) #"OOOOXOOO"
solution(8,2,["D 2","C","U 3","C","D 4","C","U 2","Z","Z","U 1","C"]) #"OOXOXOOO"                  

now_point 2
어떤 명령어?: ['D', '2']
['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
now_point 4
now_point 4
어떤 명령어?: ['C']
['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 5
now_point 5
어떤 명령어?: ['U', '3']
['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 1
now_point 1
어떤 명령어?: ['C']
['O' 'X' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 2
now_point 2
어떤 명령어?: ['D', '4']
['O' 'X' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 7
now_point 7
어떤 명령어?: ['C']
['O' 'X' 'O' 'O' 'X' 'O' 'O' 'X']
now_point 6
now_point 6
어떤 명령어?: ['U', '2']
['O' 'X' 'O' 'O' 'X' 'O' 'O' 'X']
now_point 3
now_point 3
어떤 명령어?: ['Z']
['O' 'X' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 3
now_point 3
어떤 명령어?: ['Z']
['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 3
now_point 3
어떤 명령어?: ['U', '1']
['O' 'O' 'O' 'O' 'X' 'O' 'O' 'O']
now_point 2
now_point 2
어떤 명령어?: ['C']
['O' 'O' 'X' 'O' 'X' 'O' 'O' 'O']
now_point 3


'OOXOXOOO'