In [ ]:
def rotation(row_column_list):
    
    
    return 

In [18]:
rotated[1,4] #행*열

11

In [76]:
import numpy as np 
def solution(rows, columns, queries):
    arrange_list = np.arange(1, rows*columns+1).reshape(rows,columns)
    queries = np.array(queries)-1
    answer = []
        
    def rotation(arrange_list, query):
        x1, y1, x2, y2 = query
        rotated = arrange_list.copy()
        moved = []

        # 1. 회전하기
        for i in range(y1+1, y2+1):
            rotated[x1,i]= arrange_list[x1,i-1]
        rotated[x1,y1] = arrange_list[x1+1,y1]

        for i in range(y1, y2):
            rotated[x2,i]=  arrange_list[x2,i+1]
        rotated[x2,y2] = arrange_list[x2-1,y2]
        
        for k in range(x1+1, x2):
            rotated[k,y1] = arrange_list[k+1,y1]
            rotated[k,y2] = arrange_list[k-1,y2]

        # 2.움직인 숫자 리스트 구하기
        for i in range(y1, y2+1):
            moved.append(int(rotated[x1,i]))
            moved.append(int(rotated[x2,i]))

        for k in range(x1+1, x2):    
            moved.append(int(rotated[k,y1]))
            moved.append(int(rotated[k,y2]))

        return rotated, moved
    
    for query in queries:
        arrange_list, moved = rotation(arrange_list, query)
        answer.append(min(moved))
                                       
    return answer

# solution(6,6,[[2,2,5,4],[3,3,6,6],[5,1,6,3]]) #[8, 10, 25]
# solution(3,3,[[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]] )#[1, 1, 5, 3]
solution(100,97,[[1,1,100,97]]) #[1]

[1]

In [75]:
import numpy as np 
def solution(rows, columns, queries):
    arrange_list = np.arange(1, rows*columns+1).reshape(rows,columns)
    queries = np.array(queries)-1
    answer = []
        
    def rotation(arrange_list, query):
        print("query",query)
        x1, y1, x2, y2 = query
        rotated = arrange_list.copy()
        moved = []

        # 1. 회전하기
        for i in range(y1+1, y2+1):
            rotated[x1,i]= arrange_list[x1,i-1]
        rotated[x1,y1] = arrange_list[x1+1,y1]

        for i in range(y1, y2):
            rotated[x2,i]=  arrange_list[x2,i+1]
        rotated[x2,y2] = arrange_list[x2-1,y2]
        
        for k in range(x1+1, x2):
            rotated[k,y1] = arrange_list[k+1,y1]
            rotated[k,y2] = arrange_list[k-1,y2]

        # 2.움직인 숫자 리스트 구하기
        for i in range(y1, y2+1):
            moved.append(int(rotated[x1,i]))
            moved.append(int(rotated[x2,i]))

        for k in range(x1+1, x2):    
            moved.append(int(rotated[k,y1]))
            moved.append(int(rotated[k,y2]))

        return rotated, moved
    
    for query in queries:
        arrange_list, moved = rotation(arrange_list, query)
        print("arrange_list",arrange_list)
        answer.append(min(moved))
                                       
    return answer

# solution(6,6,[[2,2,5,4],[3,3,6,6],[5,1,6,3]]) #[8, 10, 25]
# solution(3,3,[[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]] )#[1, 1, 5, 3]
solution(100,97,[[1,1,100,97]]) #[1]

query [ 0  0 99 96]
arrange_list [[  98    1    2 ...   94   95   96]
 [ 195   99  100 ...  192  193   97]
 [ 292  196  197 ...  289  290  194]
 ...
 [9507 9411 9412 ... 9504 9505 9409]
 [9604 9508 9509 ... 9601 9602 9506]
 [9605 9606 9607 ... 9699 9700 9603]]


[1]