In [2]:
import numpy as np
import pandas as pd

In [22]:
### 데이터프레임의 색인은 배열과 다르다!  --> 배열[행][열], 데이터프레임[열][행]
board_df = pd.DataFrame([[0,0,0,0,0],
                         [0,0,1,0,3],
                         [0,2,5,0,1],
                         [4,2,4,4,2],
                         [3,5,1,3,1]])
#board.shape
board_df[4][3]

2

In [36]:
board = np.array([[0,0,0,0,0],
                 [0,0,1,0,3],
                 [0,2,5,0,1],
                 [4,2,4,4,2],
                 [3,5,1,3,1]])
board
board[4][3]

3

In [24]:
moves = np.array([1,5,3,5,1,2,1,4])

In [27]:
board[:][1]

array([0, 0, 1, 0, 3])

In [40]:
a = 3
b = 3
print(board[a,b])   # [열, 행]/ [열][행]
print(board[a][b]) #둘은 결과가 같음을 확인!


4
4


In [52]:
colum_num = 4
np.argmax(board[:,colum_num]>0)

1

In [11]:
board = np.array([[0,0,0,0,0],
                 [0,0,1,0,3],
                 [0,2,5,0,1],
                 [4,2,4,4,2],
                 [3,5,1,3,1]])

moves = np.array([1,5,3,5,1,2,1,4])

temp_bucket = np.empty(0)

for colum_num in moves:
    col_index = colum_num-1
    row_index = np.argmax(board[:,col_index]>0)
    
    get = board[row_index][col_index]
    if get !=0:
        temp_bucket = np.append(temp_bucket, get)
        board[row_index][col_index] =0
    else: pass
    
display(board)
display(temp_bucket)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 2, 4, 0, 2],
       [0, 5, 1, 3, 1]])

array([4., 3., 1., 1., 3., 2., 4.])

In [12]:

answer=0

def final_calculator(temp_bucket,first):
    global answer
    answer = first
    temp_bucket = temp_bucket*2
    cumdiv = np.divide.accumulate(temp_bucket)
    
    if ~(cumdiv==1).any():
        duple_index = np.argmax(cumdiv==1)
        temp_bucket = np.delete(temp_bucket, [duple_index-1,duple_index])
        answer+= 2
        temp_bucket = (temp_bucket/2).astype(int)
        final_calculator(temp_bucket,answer)
        
    else: temp_bucket = (temp_bucket/2).astype(int)
    
    return temp_bucket,answer

temp_bucket,answer =final_calculator(temp_bucket,0)


In [13]:
print(answer)

4


In [29]:
temp_bucket = np.array([1,2,2]).astype(float)
temtem_bucket = np.empty_like(temp_bucket)

for i in range(len(temp_bucket)):
    if i!=0: 
        temtem_bucket[i]=(temp_bucket[i]/temp_bucket[i-1])
    else: pass 
temtem_bucket

array([1., 2., 1.])