In [66]:
import numpy as np 

trials = int(input())
trial_num = trials 

#room 생성하기
room =[]
while trials>0:
    room.append([int(x) for x in list(input())])
    trials-=1
room_array = np.array(room)

num = 1
answer = []
while num<=len(room):
    count=0

    for i in range(len(room)-num+1):
        for k in range(len(room)-num+1):
            if room[i][k]==1:
                if int((room_array[i:i+num,k:k+num]).sum())==num**2:
                    count+=1

    if count!=0:
        answer.append([num,count])
    num+=1

answer = np.array(answer)
total = [ x[1] for x in answer ]
print("total:",str(sum(total)))
# answer = list(answer)
for i in range(len(answer)):
    print("size["+str(answer[i][0])+"]:",str(answer[i][1]))

4
1110
1110
0110
0000
total: 11
size[1]: 8
size[2]: 3


In [62]:
total = [ x[1] for x in answer ]
sum(total)

11

In [60]:
answer[:][1]

array([2, 3])

In [53]:
import numpy as np 

trials = int(input())
trial_num = trials 

#room 생성하기
room =[]
while trials>0:
    room.append([int(x) for x in list(input())])
    trials-=1
room_array = np.array(room)

num = 1
answer = []
while num<=len(room):
    count=0

    for i in range(len(room)-num):
        for k in range(len(room)-num):
            if room[i][k]==1:
                if int((room_array[i:i+num,k:k+num]).sum())==num**2:
                    count+=1

    if count!=0:
        answer.append([num,count])
    num+=1

answer = np.array(answer)
print(answer)

print("total:"+str(answer.sum()))
# answer = list(answer)
for i in range(len(answer)):
    print("size["+str(answer[i][0])+"]:"+str(answer[i][1]))

4
1110
1110
0110
0000
[[1 8]
 [2 3]]
total:14
size[1]:8
size[2]:3


In [46]:
answer = np.array(answer)
answer.sum()

14

In [41]:
num = 1
answer = []
while num<=len(room):
    count=0

    for i in range(len(room)-num):
        for k in range(len(room)-num):
            if room[i][k]==1:
                if int((room_array[i:i+num,k:k+num]).sum())==num**2:
                    count+=1

    if count!=0:
        answer.append([num,count])
    num+=1
print(answer)

[[1, 8], [2, 3]]


In [18]:
a = [x + y for x, y in zip(a,b)]

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [27]:
room

[[1, 1, 1, 0], [1, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]

In [34]:
room_array = np.array(room)
len(room_array)

4

In [35]:
i,k =1,1
room_array[i:i+2,k:k+2]

array([[1, 1],
       [1, 1]])

In [36]:
count=0
num =2
room_array = np.array(room)
for i in range(len(room)-num):
    for k in range(len(room)-num):
        if room[i][k]==1:
            if int((room_array[i:i+2,k:k+2]).sum())==num**2:
                count+=1
            
print(count)

3


In [9]:
# 위쪽 1개행, 아래쪽 2개행, 왼쪽 3개열, 오른족 4개열 0으로 패딩합니다
np.pad(bb, ((1,2),(3,4)), 'constant', constant_values=0)

NameError: name 'np' is not defined

In [6]:
room,sum()

[[1, 1, 1, 0], [1, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]

In [ ]:
import sys
a = int(sys.stdin.readline())