#### 문제 설명
- n개의 섬 사이에 다리를 건설하는 비용(costs)이 주어질 때, 최소의 비용으로 모든 섬이 서로 통행 가능하도록 만들 때 필요한 최소 비용을 return 하도록 solution을 완성하세요.

- 다리를 여러 번 건너더라도, 도달할 수만 있으면 통행 가능하다고 봅니다. 예를 들어 A 섬과 B 섬 사이에 다리가 있고, B 섬과 C 섬 사이에 다리가 있으면 A 섬과 C 섬은 서로 통행 가능합니다.

#### 제한사항

- 섬의 개수 n은 1 이상 100 이하입니다.
- costs의 길이는 ((n-1) * n) / 2이하입니다.
- 임의의 i에 대해, costs[i][0] 와 costs[i] [1]에는 다리가 연결되는 두 섬의 번호가 들어있고, costs[i] [2]에는 이 두 섬을 연결하는 다리를 건설할 때 드는 비용입니다.
- 같은 연결은 두 번 주어지지 않습니다. 또한 순서가 바뀌더라도 같은 연결로 봅니다. 즉 0과 1 사이를 연결하는 비용이 주어졌을 때, 1과 0의 비용이 주어지지 않습니다.
- 모든 섬 사이의 다리 건설 비용이 주어지지 않습니다. 이 경우, 두 섬 사이의 건설이 불가능한 것으로 봅니다.
- 연결할 수 없는 섬은 주어지지 않습니다.

In [84]:
a = [8, 5, 2, 1, 1]

list(filter(lambda x:a[x]==min(a),range(len(a))))

[3, 4]

## 1. 초기값으로 모든 way 를 넣어본다.

#### - 한 문제 더 맞췄지만, 나머지 4문제는 틀림

In [144]:
def solution(n, costs):
    answer = []
    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
    
    
    for start_way in cost_way:
        cost_way = [tuple(x[:2]) for x in costs]
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        cost_way.remove(start_way)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            if set(min_way).intersection(set(connected_group))!=set(min_way):            
                connected_group.extend(list(min_way))
                connected_group = list(set(connected_group))
                total_cost+= way_cost_dict[min_way]
            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    return min(answer)

{(2, 3): 8, (1, 2): 5, (1, 3): 1}
dict_items([((0, 1), 1), ((1, 2), 8), ((1, 3), 8), ((2, 3), 8)])


[(1, 2), (1, 3), (2, 3)]

In [153]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.05ms, 10.2MB)
# 테스트 2 〉	통과 (0.10ms, 10.3MB)
# 테스트 3 〉	실패 (2.98ms, 10.1MB)
# 테스트 4 〉	실패 (13.94ms, 10.3MB)
# 테스트 5 〉	실패 (2.20ms, 10.2MB)
# 테스트 6 〉	통과 (37.08ms, 10.2MB)
# 테스트 7 〉	실패 (130.25ms, 10.2MB)
# 테스트 8 〉	통과 (0.82ms, 10.3MB)

def solution(n, costs):
    answer = []
    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
    
    
    for start_way in cost_way:
        ##초기화
        print("시작한다","="*60,"start_way",start_way)
        
        cost_way = [tuple(x[:2]) for x in costs]
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        print("way_cost_dict",way_cost_dict)
        cost_way.remove(start_way)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            print("connected_group",connected_group)
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            if set(min_way).intersection(set(connected_group))!=set(min_way):            
                connected_group.extend(list(min_way))
                connected_group = list(set(connected_group))
                total_cost+= way_cost_dict[min_way]
            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution(5, [[0,1,5],[1,2,3],[2,3,3],[3,1,2],[3,0,4],[2,4,6],[4,0,7]])

시작한다 ============================================================ start_way (0, 1)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [0, 1]
connected_group [0, 1, 3]
connected_group [0, 1, 2, 3]
connected_group [0, 1, 2, 3]
connected_group [0, 1, 2, 3]
시작한다 ============================================================ start_way (1, 2)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [1, 2]
connected_group [1, 2, 3]
connected_group [1, 2, 3]
connected_group [0, 1, 2, 3]
connected_group [0, 1, 2, 3]
시작한다 ============================================================ start_way (2, 3)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [2, 3]
connected_group [1, 2, 3]
connected_group [1, 2, 3]
connected_group [0, 1, 2, 3]
connected_group [0, 1, 2, 3]
시작한다 ============================================================ start_w

15

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.05ms, 10.2MB)
# 테스트 2 〉	통과 (0.10ms, 10.3MB)
# 테스트 3 〉	실패 (2.98ms, 10.1MB)
# 테스트 4 〉	실패 (13.94ms, 10.3MB)
# 테스트 5 〉	실패 (2.20ms, 10.2MB)
# 테스트 6 〉	통과 (37.08ms, 10.2MB)
# 테스트 7 〉	실패 (130.25ms, 10.2MB)
# 테스트 8 〉	통과 (0.82ms, 10.3MB)

def solution(n, costs):
    answer = []
    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
    
    
    for start_way in cost_way:
        ##초기화
        print("시작한다","="*60,"start_way",start_way)
        
        cost_way = [tuple(x[:2]) for x in costs]
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        print("way_cost_dict",way_cost_dict)
        cost_way.remove(start_way)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            print("connected_group",connected_group)
            priority_ways =[]
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            min_cost = way_cost_dict[min_way]
            priority_ways = [key for key, val in way_cost_dict.items() if val ==min_cost]
            
            if priority_ways:
                min_way = priority_ways.pop()
            
            print("candidate_ways",candidate_ways)
            print("min_way",min_way)
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution(5, [[0,1,5],[1,2,3],[2,3,3],[3,1,2],[3,0,4],[2,4,6],[4,0,7]])

In [151]:

def solution(n, costs):
    answer =[]
    def get_min_way_rightnow(connected_group,cost_way,way_cost_dict,total_cost, n):
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            print("candidate_ways",candidate_ways)
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            min_cost = way_cost_dict[min_way]
            min_ways_list = [key for key, val in way_cost_dict.items() if val ==min_cost]
            
            if len(min_ways_list) ==1:
                connected_group.extend(list(min_ways_list))
                connected_group = list(set(connected_group))
                total_cost+= way_cost_dict[min_ways_list]
                del way_cost_dict[min_ways_list]
                cost_way.remove(min_ways_list)
            else:
                for ways in min_ways_list:
                    connected_group.extend(list(min_ways_list))
                    connected_group = list(set(connected_group))
                    total_cost+= way_cost_dict[min_ways_list]
                    del way_cost_dict[min_ways_list]
                    cost_way.remove(min_ways_list)
                    
                    while len(connected_group)!=n:
                        connected_group,cost_way,way_cost_dict,total_cost, n =\
                            get_min_way_rightnow(connected_group,cost_way,way_cost_dict,total_cost, n)
                    answer.append(total_cost)
                    
        answer.append(total_cost)
        
        return connected_group,cost_way,way_cost_dict,total_cost, n
    
    answer = []
    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init

    for start_way in cost_way:
        ##초기화
        cost_way = [tuple(x[:2]) for x in costs]
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        cost_way.remove(start_way)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        print("start_way",start_way,"="*60,"시작한다")
        print("way_cost_dict", way_cost_dict)
        
        min_ways_list = get_min_way_rightnow(connected_group,cost_way,way_cost_dict,n)
        if len(min_ways_list)==1:
            connected_group.extend(list(min_ways_list))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_ways_list]
            del way_cost_dict[min_ways_list]
            cost_way.remove(min_ways_list)
            
        else:
            
        answer.append(total_cost)
    print(answer)
    return min(answer)

# solution( 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]])
solution( 4, [[0,1,1],[0,2,1],[1,2,5],[1,3,1],[2,3,8]])

시작한다 ============================================================ start_way (0, 1)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [0, 1]
candidate_ways [(3, 0), (4, 0), (1, 2), (3, 1)]
min_way (3, 1)
connected_group [0, 1, 3]
candidate_ways [(3, 0), (4, 0), (1, 2), (2, 3), (3, 0)]
min_way (1, 2)
connected_group [0, 1, 2, 3]
candidate_ways [(3, 0), (4, 0), (2, 3), (2, 4), (2, 3), (3, 0)]
min_way (2, 3)
connected_group [0, 1, 2, 3]
candidate_ways [(3, 0), (4, 0), (2, 4), (3, 0)]
min_way (3, 0)
connected_group [0, 1, 2, 3]
candidate_ways [(4, 0), (2, 4)]
min_way (2, 4)
시작한다 ============================================================ start_way (1, 2)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [1, 2]
candidate_ways [(0, 1), (3, 1), (2, 3), (2, 4)]
min_way (3, 1)
connected_group [1, 2, 3]
candidate_ways [(0, 1), (2, 3), (2, 4), (2, 3), (3, 0)]
min_way (2, 3)
connecte

16

In [148]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.05ms, 10.2MB)
# 테스트 2 〉	통과 (0.10ms, 10.3MB)
# 테스트 3 〉	실패 (2.98ms, 10.1MB)
# 테스트 4 〉	실패 (13.94ms, 10.3MB)
# 테스트 5 〉	실패 (2.20ms, 10.2MB)
# 테스트 6 〉	통과 (37.08ms, 10.2MB)
# 테스트 7 〉	실패 (130.25ms, 10.2MB)
# 테스트 8 〉	통과 (0.82ms, 10.3MB)

def solution(n, costs):
    answer = []
    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
    
    
    for start_way in cost_way:
        ##초기화
        print("시작한다","="*60,"start_way",start_way)
        
        cost_way = [tuple(x[:2]) for x in costs]
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        print("way_cost_dict",way_cost_dict)
        cost_way.remove(start_way)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            print("connected_group",connected_group)
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            print("candidate_ways",candidate_ways)
            print("min_way",min_way)
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution(5, [[0,1,5],[1,2,3],[2,3,3],[3,1,2],[3,0,4],[2,4,6],[4,0,7]])

시작한다 ============================================================ start_way (0, 1)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [0, 1]
candidate_ways [(3, 0), (4, 0), (1, 2), (3, 1)]
min_way (3, 1)
connected_group [0, 1, 3]
candidate_ways [(3, 0), (4, 0), (1, 2), (2, 3), (3, 0)]
min_way (1, 2)
connected_group [0, 1, 2, 3]
candidate_ways [(3, 0), (4, 0), (2, 3), (2, 4), (2, 3), (3, 0)]
min_way (2, 3)
connected_group [0, 1, 2, 3]
candidate_ways [(3, 0), (4, 0), (2, 4), (3, 0)]
min_way (3, 0)
connected_group [0, 1, 2, 3]
candidate_ways [(4, 0), (2, 4)]
min_way (2, 4)
시작한다 ============================================================ start_way (1, 2)
way_cost_dict {(0, 1): 5, (1, 2): 3, (2, 3): 3, (3, 1): 2, (3, 0): 4, (2, 4): 6, (4, 0): 7}
connected_group [1, 2]
candidate_ways [(0, 1), (3, 1), (2, 3), (2, 4)]
min_way (3, 1)
connected_group [1, 2, 3]
candidate_ways [(0, 1), (2, 3), (2, 4), (2, 3), (3, 0)]
min_way (2, 3)
connecte

16

## 1. 초기값으로 모든 way를 넣어본다
####  - 정정: way로 잘 시작했음
####  - 오류: 다음 최소값을 찾는 작업에서, 최소값이 다중일때, 처음 index것만 불러옴! 

In [145]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.05ms, 10.2MB)
# 테스트 2? 〉	통과 (0.10ms, 10.3MB)
# 테스트 3 〉	실패 (2.98ms, 10.1MB)
# 테스트 4 〉	실패 (13.94ms, 10.3MB)
# 테스트 5 〉	실패 (2.20ms, 10.2MB)
# 테스트 6 〉	통과 (37.08ms, 10.2MB)
# 테스트 7 〉	실패 (130.25ms, 10.2MB)
# 테스트 8 〉	통과 (0.82ms, 10.3MB)

def solution(n, costs):
    answer = []
    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
    
    
    for start_way in cost_way:
        ##초기화
        print("시작한다","="*60,"start_way",start_way)
        print("way_cost_dict",way_cost_dict)
        cost_way = [tuple(x[:2]) for x in costs]
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        cost_way.remove(start_way)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution(5, [[0,1,5],[1,2,3],[2,3,3],[3,1,2],[3,0,4],[2,4,6],[4,0,7]])

[23, 23, 23, 23, 23, 18, 16]


16

## 1. 초기값으로 모든 way를 넣어본다
####  - 오류: way로 시작한것이 아니라 index로 시작해서 논리가 맞지 않음

In [123]:
# 확성  테스트
# 테스트 1 〉	통과 (0.05ms, 10.3MB)
# 테스트 2 〉	실패 (런타임 에러)
# 테스트 3 〉	실패 (1.83ms, 10.3MB)
# 테스트 4 〉	실패 (8.38ms, 10.2MB)
# 테스트 5 〉	실패 (1.21ms, 10.3MB)
# 테스트 6 〉	통과 (8.26ms, 10.2MB)
# 테스트 7 〉	실패 (28.58ms, 10.3MB)
# 테스트 8 〉	통과 (0.43ms, 10.3MB)

def solution(n, costs):
    answer = []
    for start_idx in range(n):
        ##초기화
        cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}

        start_way = cost_way.pop(start_idx)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution( 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]])

[4, 4, 7, 4]


4

#### 가장 노드가 많은 섬의 최소 비용 길을 먼저 가자

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.11ms, 27.6MB)
# 테스트 2 〉	통과 (0.62ms, 27.6MB)
# 테스트 3 〉	실패 (1.35ms, 27.4MB)
# 테스트 4 〉	실패 (3.11ms, 27.4MB)
# 테스트 5 〉	실패 (1.08ms, 27.9MB)
# 테스트 6 〉	실패 (0.74ms, 27.6MB)
# 테스트 7 〉	실패 (8.62ms, 27.4MB)
# 테스트 8 〉	통과 (0.26ms, 28MB)

import numpy as np
from collections import Counter

def solution(n, costs):
    total_bags=[]
    cost_way = [tuple(x[:2]) for x in costs]
    for i in range(len(cost_way)):
        total_bags.append(cost_way[i][0])
        print("cost_way[i][0]",cost_way[i][0])
        total_bags.append(cost_way[i][1])
    most_common = Counter(total_bags).most_common(1)
    print("total_bags",total_bags)
    print("most_common",most_common)
    
    answer = []
    for start_way in most_common:
        ##초기화
        cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}

        start_way = cost_way.pop(start_idx)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution( 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]])

In [121]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.11ms, 27.6MB)
# 테스트 2 〉	통과 (0.62ms, 27.6MB)
# 테스트 3 〉	실패 (1.35ms, 27.4MB)
# 테스트 4 〉	실패 (3.11ms, 27.4MB)
# 테스트 5 〉	실패 (1.08ms, 27.9MB)
# 테스트 6 〉	실패 (0.74ms, 27.6MB)
# 테스트 7 〉	실패 (8.62ms, 27.4MB)
# 테스트 8 〉	통과 (0.26ms, 28MB)

import numpy as np


def solution(n, costs):
    total_bags=[]
    cost_way = [tuple(x[:2]) for x in costs]
    for i in cost_way:
        total_bags.append(i[0])
        total_bags.append(i[1])
        
    
    
    answer = []
    for start_idx in start_tmp:
        ##초기화
        cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}

        start_way = cost_way.pop(start_idx)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

solution( 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]])

TypeError: only integer scalar arrays can be converted to a scalar index

#### 초기화 값 조건 없이 다 돌려보자

In [97]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.05ms, 10.3MB)
# 테스트 2 〉	실패 (런타임 에러)
# 테스트 3 〉	실패 (1.83ms, 10.3MB)
# 테스트 4 〉	실패 (8.38ms, 10.2MB)
# 테스트 5 〉	실패 (1.21ms, 10.3MB)
# 테스트 6 〉	통과 (8.26ms, 10.2MB)
# 테스트 7 〉	실패 (28.58ms, 10.3MB)
# 테스트 8 〉	통과 (0.43ms, 10.3MB)

def solution(n, costs):
    answer = []
    for start_idx in range(n):
        ##초기화
        cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}

        start_way = cost_way.pop(start_idx)
        connected_group  = list(start_way)
        total_cost=way_cost_dict[start_way]
        del way_cost_dict[start_way]
        
        while len(connected_group)!=n:
            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print(answer)
    return min(answer)

4

In [94]:
import numpy as np

def solution(n, costs):
    costs.sort(key = lambda x : x[2], reverse = True) 
    connected_group = []
    total_cost = 0

    cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
    cost_cost = [x[2] for x in costs]
    print("cost_cost",cost_cost)
    
    start_candidate = list(filter(lambda x:cost_cost[x]==min(cost_cost),range(len(cost_cost))))
    print("start_candidate",start_candidate)
    
    way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
    
    answer = []
    for start_idx in start_candidate:
        print("첫버째 후보 시작한다!!!!!","start_idx",start_idx )
        ##초기화시작
        connected_group = []
        total_cost = 0
        cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
        ## 초기화 끝 
        start_way = cost_way.pop(start_idx)
        connected_group.extend(start_way)
        total_cost+=way_cost_dict[start_way]
    
        

        while len(connected_group)!=n:
            print("="*80,"루프시작")
            print("connected_group",connected_group)
            print("total_cost",total_cost)
            print("cost_way",cost_way)
            print("way_cost_dict",way_cost_dict)

            candidate_ways =[]
            for i in connected_group:
                candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))

            print("candidate_ways",candidate_ways)
            min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])

            print("min_way",min_way)
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]

            del way_cost_dict[min_way]
            cost_way.remove(min_way)
        answer.append(total_cost)
    print("answer",answer)
    return min(answer)

solution( 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]])

cost_cost [8, 5, 2, 1, 1]
start_candidate [3, 4]
첫버째 후보 시작한다!!!!! start_idx 3
================================================================================ 루프시작
connected_group [0, 1]
total_cost 1
cost_way [(2, 3), (1, 2), (0, 2), (1, 3)]
way_cost_dict {(2, 3): 8, (1, 2): 5, (0, 2): 2, (0, 1): 1, (1, 3): 1}
candidate_ways [(0, 2), (1, 2), (1, 3)]
min_way (1, 3)
================================================================================ 루프시작
connected_group [0, 1, 3]
total_cost 2
cost_way [(2, 3), (1, 2), (0, 2)]
way_cost_dict {(2, 3): 8, (1, 2): 5, (0, 2): 2, (0, 1): 1}
candidate_ways [(0, 2), (1, 2), (2, 3)]
min_way (0, 2)
첫버째 후보 시작한다!!!!! start_idx 4
================================================================================ 루프시작
connected_group [1, 3]
total_cost 1
cost_way [(2, 3), (1, 2), (0, 2), (0, 1)]
way_cost_dict {(2, 3): 8, (1, 2): 5, (0, 2): 2, (0, 1): 1, (1, 3): 1}
candidate_ways [(1, 2), (0, 1), (2, 3)]
min_way (0, 1)
==========================================

4

In [63]:
import numpy as np
n, costs = 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]

costs.sort(key = lambda x : x[2], reverse = True) 
connected_group = []
total_cost = 0

cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
way_cost_dict = {tuple(x[:2]):x[2] for x in costs}

start = cost_way.pop()
connected_group.extend(start)
total_cost+=way_cost_dict[start]

while len(connected_group)!=n:
    candidate_ways =[]
    for i in connected_group:
        candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
    
    min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
    
    connected_group.extend(list(min_way))
    connected_group = list(set(connected_group))
    total_cost+= way_cost_dict[min_way]
    
    del way_cost_dict[min_way]
    cost_way.remove(min_way)

print(total_cost)

4


In [59]:
import numpy as np
n, costs = 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]

costs.sort(key = lambda x : x[2], reverse = True) 
connected_group = []
total_cost = 0

print("costs", costs)
cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
print(way_cost_dict)

start = cost_way.pop()
connected_group.extend(start)
total_cost+=way_cost_dict[start]

print("cost_way",cost_way)

candidate_ways =[]
for i in connected_group:
    candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
print("candidate_ways", candidate_ways)

min_way = min(candidate_ways, key = lambda x: way_cost_dict[x])
print("min_way",min_way)

print("connected_group",connected_group)
print("total_cost",total_cost)

connected_group.extend(list(min_way))
connected_group = set(connected_group)
total_cost+= way_cost_dict[min_way]

print("connected_group",connected_group)
print("total_cost",total_cost)

print("way_cost_dict", way_cost_dict)
del way_cost_dict[min_way]
print("way_cost_dict", way_cost_dict)

costs [[2, 3, 8], [1, 2, 5], [0, 2, 2], [0, 1, 1], [1, 3, 1]]
{(2, 3): 8, (1, 2): 5, (0, 2): 2, (0, 1): 1, (1, 3): 1}
cost_way [(2, 3), (1, 2), (0, 2), (0, 1)]
candidate_ways [(1, 2), (0, 1), (2, 3)]
min_way (0, 1)
connected_group [1, 3]
total_cost 1
connected_group {0, 1, 3}
total_cost 2
way_cost_dict {(2, 3): 8, (1, 2): 5, (0, 2): 2, (0, 1): 1, (1, 3): 1}
way_cost_dict {(2, 3): 8, (1, 2): 5, (0, 2): 2, (1, 3): 1}


In [24]:
import numpy as np
n, costs = 4, [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]

node_cnt_0 = np.zeros((n,n)).astype('int')
for i,j,val in costs:
    node_cnt_0[i][j], node_cnt_0[j][i] = val, val

node_cnt_999 = np.where(node_cnt_0==0,999,node_cnt_0)
way_cnt = np.where(node_cnt_0!=0,1,0)

print(node_cnt_0)
print(way_cnt)
way_cnt1 = way_cnt.sum(axis=1)
start_tmp = np.where(way_cnt1 == way_cnt1.min())

# for i in start_tmp:

i = start_tmp[0][0]
print("i",i)
print(node_cnt_999[i].argmin())

[[0 1 2 0]
 [1 0 5 1]
 [2 5 0 8]
 [0 1 8 0]]
[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 1]
 [0 1 1 0]]
i 0
1
