#### 문제 설명
- 네오는 평소 프로도가 비상금을 숨겨놓는 장소를 알려줄 비밀지도를 손에 넣었다. 그런데 이 비밀지도는 숫자로 암호화되어 있어 위치를 확인하기 위해서는 암호를 해독해야 한다. 다행히 지도 암호를 해독할 방법을 적어놓은 메모도 함께 발견했다.

- 지도는 한 변의 길이가 n인 정사각형 배열 형태로, 각 칸은 "공백"(" ") 또는 "벽"("#") 두 종류로 이루어져 있다.
- 전체 지도는 두 장의 지도를 겹쳐서 얻을 수 있다. 각각 "지도 1"과 "지도 2"라고 하자. 지도 1 또는 지도 2 중 어느 하나라도 벽인 부분은 전체 지도에서도 벽이다. 지도 1과 지도 2에서 모두 공백인 부분은 전체 지도에서도 공백이다.
- "지도 1"과 "지도 2"는 각각 정수 배열로 암호화되어 있다.
- 암호화된 배열은 지도의 각 가로줄에서 벽 부분을 1, 공백 부분을 0으로 부호화했을 때 얻어지는 이진수에 해당하는 값의 배열이다.

-> 네오가 프로도의 비상금을 손에 넣을 수 있도록, 비밀지도의 암호를 해독하는 작업을 도와줄 프로그램을 작성하라.

#### 입력 형식
- 입력으로 지도의 한 변 크기 n 과 2개의 정수 배열 arr1, arr2가 들어온다.

- 1 ≦ n ≦ 16
- arr1, arr2는 길이 n인 정수 배열로 주어진다.
- 정수 배열의 각 원소 x를 이진수로 변환했을 때의 길이는 n 이하이다. 즉, 0 ≦ x ≦ 2n - 1을 만족한다.

### 풀이 계획
1) 배열을 이진수로 바꾼다

2) 이진수를 넘파이를 사용한 조건식으로 답을 구한다

### 0을 예외처리를 잘못해서 못풀었던것으로!

In [72]:
# https://www.crocus.co.kr/1660
print("aaa".rjust(5,"0")) #오른쪽 정렬
print("aaa".ljust(5,"0")) #왼쪽 정렬
print("2".zfill(3)) #왼쪽에 0을 채워줌

00aaa
aaa00
002


In [69]:
100|1

101

In [60]:
bin(10)

'0b1010'

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.30ms, 27MB)
# 테스트 2 〉	통과 (0.82ms, 27.6MB)
# 테스트 3 〉	통과 (3.38ms, 27.6MB)
# 테스트 4 〉	통과 (0.34ms, 28MB)
# 테스트 5 〉	통과 (0.22ms, 27.9MB)
# 테스트 6 〉	통과 (0.48ms, 27.6MB)
# 테스트 7 〉	통과 (0.18ms, 27.7MB)
# 테스트 8 〉	통과 (1.43ms, 27.7MB)
# 채점 결과

In [57]:
import math
import numpy as np

def solution(n, arr1, arr2):
    
    def to_binary_num(num_10):
        if num_10 ==0:
            return 1,['0']
        digits=math.floor(math.log2(num_10))
        num_2_str = ""

        for i in range(digits,-1,-1):
            if num_10>=2**i:
                num_10-=2**i
                num_2_str+=str(1)
            else:
                num_2_str+=str(0)
        num2_list = list(num_2_str)
        num2_len = len(num2_list)     
        return num2_len, num2_list

    def arr_to_map(arr):
        arr1 = arr
        arr1_num2 = [to_binary_num(x)[1] for x in arr1]
        arr1_len = max([to_binary_num(x)[0] for x in arr1])
        for i in range(len(arr1_num2)):
            if len(arr1_num2[i])<arr1_len:
                arr1_num2[i] = ['0']*(arr1_len-len(arr1_num2[i]))+arr1_num2[i]
            arr1_num2[i] = [int(x) for x in arr1_num2[i]]
        return arr1_num2
    
    arr1_map = np.array(arr_to_map(arr1))
    arr2_map = np.array(arr_to_map(arr2))
    
    total_map = arr1_map+arr2_map
    total_map = np.where(total_map>=1,"#"," ")
    
    answer = [ "".join(x) for x in total_map]
    return answer


### 런타임 에러가 났다. 어디선가 예외처리를 해야하는 부분이 있나보다

In [4]:
# 정확성  테스트
# 테스트 1 〉	실패 (런타임 에러)
# 테스트 2 〉	통과 (0.81ms, 27.9MB)
# 테스트 3 〉	실패 (런타임 에러)
# 테스트 4 〉	통과 (0.35ms, 28MB)
# 테스트 5 〉	통과 (2.32ms, 27.6MB)
# 테스트 6 〉	통과 (0.45ms, 27.7MB)
# 테스트 7 〉	통과 (0.18ms, 27.6MB)
# 테스트 8 〉	통과 (0.14ms, 27.5MB)

[0, 0]

In [33]:
import math
import numpy as np
def solution(n, arr1, arr2):
    
    def to_binary_num(num_10):
        digits=math.floor(math.log2(num_10))
        num_2_str = ""

        for i in range(digits,-1,-1):
            if num_10>=2**i:
                num_10-=2**i
                num_2_str+=str(1)
            else:
                num_2_str+=str(0)
        num2_list = list(num_2_str)
        num2_len = len(num2_list)     
        
        print(num2_list)
        print(num2_len)
        return num2_len, num2_list

    def arr_to_map(arr):
        arr1 = arr
        arr1_num2 = [to_binary_num(x)[1] for x in arr1]
        arr1_len = max([to_binary_num(x)[0] for x in arr1])

        for i in range(len(arr1_num2)):
            if len(arr1_num2[i])<arr1_len:
                arr1_num2[i] = ['0']*(arr1_len-len(arr1_num2[i]))+arr1_num2[i]
            arr1_num2[i] = [int(x) for x in arr1_num2[i]]
        return arr1_num2
    
    arr1_map = np.array(arr_to_map(arr1))
    arr2_map = np.array(arr_to_map(arr2))
    
    total_map = arr1_map+arr2_map
    total_map = np.where(total_map>=1,"#"," ")
    print(arr1_map)
    print(arr2_map)
    print("total_map",total_map)
    
    answer = [ "".join(x) for x in total_map]
    return answer

solution(5, [9, 20, 28, 18, 11],[30, 1, 21, 17, 28]) 
#["#####","# # #", "### #", "# ##", "#####"]
# solution(6, [46, 33, 33 ,22, 31, 50],[27 ,56, 19, 14, 14, 10]) 
#["######", "### #", "## ##", " #### ", " #####", "### # "]

['1', '0', '0', '1']
4
['1', '0', '1', '0', '0']
5
['1', '1', '1', '0', '0']
5
['1', '0', '0', '1', '0']
5
['1', '0', '1', '1']
4
['1', '0', '0', '1']
4
['1', '0', '1', '0', '0']
5
['1', '1', '1', '0', '0']
5
['1', '0', '0', '1', '0']
5
['1', '0', '1', '1']
4
['1', '1', '1', '1', '0']
5
['1']
1
['1', '0', '1', '0', '1']
5
['1', '0', '0', '0', '1']
5
['1', '1', '1', '0', '0']
5
['1', '1', '1', '1', '0']
5
['1']
1
['1', '0', '1', '0', '1']
5
['1', '0', '0', '0', '1']
5
['1', '1', '1', '0', '0']
5
[[0 1 0 0 1]
 [1 0 1 0 0]
 [1 1 1 0 0]
 [1 0 0 1 0]
 [0 1 0 1 1]]
[[1 1 1 1 0]
 [0 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 1 0 0]]
total_map [['#' '#' '#' '#' '#']
 ['#' ' ' '#' ' ' '#']
 ['#' '#' '#' ' ' '#']
 ['#' ' ' ' ' '#' '#']
 ['#' '#' '#' '#' '#']]


['#####', '# # #', '### #', '#  ##', '#####']