#### 문제 설명
- 일렬로 나열된 n개의 풍선이 있습니다. 모든 풍선에는 서로 다른 숫자가 써져 있습니다. 당신은 다음 과정을 반복하면서 풍선들을 단 1개만 남을 때까지 계속 터트리려고 합니다.

    1. 임의의 인접한 두 풍선을 고른 뒤, 두 풍선 중 하나를 터트립니다.
    2. 터진 풍선으로 인해 풍선들 사이에 빈 공간이 생겼다면, 빈 공간이 없도록 풍선들을 중앙으로 밀착시킵니다.
    
    
- 여기서 조건이 있습니다. 인접한 두 풍선 중에서 번호가 더 작은 풍선을 터트리는 행위는 최대 1번만 할 수 있습니다. 즉, 어떤 시점에서 인접한 두 풍선 중 번호가 더 작은 풍선을 터트렸다면, 그 이후에는 인접한 두 풍선을 고른 뒤 번호가 더 큰 풍선만을 터트릴 수 있습니다.

- 당신은 어떤 풍선이 최후까지 남을 수 있는지 알아보고 싶습니다. 위에 서술된 조건대로 풍선을 터트리다 보면, 어떤 풍선은 최후까지 남을 수도 있지만, 어떤 풍선은 무슨 수를 쓰더라도 마지막까지 남기는 것이 불가능할 수도 있습니다.

- 일렬로 나열된 풍선들의 번호가 담긴 배열 a가 주어집니다. 위에 서술된 규칙대로 풍선들을 1개만 남을 때까지 터트렸을 때 최후까지 남기는 것이 가능한 풍선들의 개수를 return 하도록 solution 함수를 완성해주세요.

#### 제한 사항
- a의 길이는 1 이상 1,000,000 이하입니다.
- a[i]는 i+1 번째 풍선에 써진 숫자를 의미합니다.
- a의 모든 수는 -1,000,000,000 이상 1,000,000,000 이하인 정수입니다.
- a의 모든 수는 서로 다릅니다.

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.04ms, 27.5MB)
# 테스트 2 〉	통과 (0.03ms, 27.8MB)
# 테스트 3 〉	통과 (0.26ms, 27.7MB)
# 테스트 4 〉	통과 (26.84ms, 32.6MB)
# 테스트 5 〉	통과 (149.79ms, 54.3MB)
# 테스트 6 〉	통과 (219.14ms, 67.8MB)
# 테스트 7 〉	통과 (314.62ms, 81.4MB)
# 테스트 8 〉	통과 (304.26ms, 81.4MB)
# 테스트 9 〉	통과 (307.87ms, 81.3MB)
# 테스트 10 〉	통과 (311.00ms, 81.4MB)
# 테스트 11 〉	통과 (567.69ms, 81.2MB)
# 테스트 12 〉	통과 (487.11ms, 81.1MB)
# 테스트 13 〉	통과 (432.26ms, 81.5MB)
# 테스트 14 〉	통과 (530.08ms, 81.4MB)
# 테스트 15 〉	통과 (569.84ms, 81.3MB)

In [11]:
import numpy as np

def solution(a):
    a = np.array(a)
    argsort_a = np.argsort(a)
    answer = 2
    
    left_min_idx = min(argsort_a[0],argsort_a[1])
    right_min_idx = max(argsort_a[0],argsort_a[1])
    
    for i in argsort_a[2:]:
        if left_min_idx< i <right_min_idx:
            pass
        else:
            answer+=1
            left_min_idx = min(left_min_idx, i)
            right_min_idx = max(right_min_idx, i)
            
    return answer

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])


3

값이 작은 순서대로 뽑아서 그 사이에 있는 값을 0으로 만드는 방법을 썼는데, 

1번문제는 틀릴뿐만 아니라, 시간초과도 났다

In [6]:
import numpy as np

def solution(a):
    a = np.array(a)
    argsort_a = np.argsort(a)
    answer = 1
    
    for i in range(1,len(argsort_a)):
        if argsort_a[0]<argsort_a[i]:
            a[argsort_a[0]+1:argsort_a[i]+1]=1000000001
            print(a)
        else: 
            a[argsort_a[i]:argsort_a[0]]=1000000001
            print(a)
        answer+=1
        print("answer추가: ",answer)
        print(a)
        if len(a[np.where(a!=1000000001)])==1:
            print("이제 끝난다 ")
            break
    
    return answer

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])


[       -16         27         65         -2         58        -92
 1000000001        -68        -61        -33]
answer추가:  2
[       -16         27         65         -2         58        -92
 1000000001        -68        -61        -33]
[       -16         27         65         -2         58        -92
 1000000001 1000000001        -61        -33]
answer추가:  3
[       -16         27         65         -2         58        -92
 1000000001 1000000001        -61        -33]
[       -16         27         65         -2         58        -92
 1000000001 1000000001 1000000001        -33]
answer추가:  4
[       -16         27         65         -2         58        -92
 1000000001 1000000001 1000000001        -33]
[       -16         27         65         -2         58        -92
 1000000001 1000000001 1000000001 1000000001]
answer추가:  5
[       -16         27         65         -2         58        -92
 1000000001 1000000001 1000000001 1000000001]
[1000000001 1000000001 1000000001 1000000001

6

In [1]:
import numpy as np

def solution(a):
    a = np.array(a)
    argsort_a = np.argsort(a)
    answer = 1
    
    for i in range(1,len(argsort_a)):
        if argsort_a[0]<argsort_a[i]:
            a[argsort_a[0]+1:argsort_a[i]+1]=0
            print(a)
        else: 
            a[argsort_a[i]:argsort_a[0]]=0
            print(a)
        answer+=1
        print("answer추가: ",answer)
        print(a)
        if len(a[np.where(a!=0)])==1:
            print("이제 끝난다 ")
            break
    
    return answer

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])


[-16  27  65  -2  58 -92   0 -68 -61 -33]
answer추가:  2
[-16  27  65  -2  58 -92   0 -68 -61 -33]
[-16  27  65  -2  58 -92   0   0 -61 -33]
answer추가:  3
[-16  27  65  -2  58 -92   0   0 -61 -33]
[-16  27  65  -2  58 -92   0   0   0 -33]
answer추가:  4
[-16  27  65  -2  58 -92   0   0   0 -33]
[-16  27  65  -2  58 -92   0   0   0   0]
answer추가:  5
[-16  27  65  -2  58 -92   0   0   0   0]
[  0   0   0   0   0 -92   0   0   0   0]
answer추가:  6
[  0   0   0   0   0 -92   0   0   0   0]
이제 끝난다 


6

In [19]:
a = [9,-1,-5] #3
a = [-16,27,65,-2,58,-92,-71,-68,-61,-33] #6 - 16, -92, -71, -68, -61, -33
a = np.array(a)
a[5:2]=0
a

array([-16,  27,  65,  -2,  58, -92, -71, -68, -61, -33])

min_a 비교 예외처리 안했을때

In [11]:
def solution(a):
    answer =2
    last_idx = len(a)-1
    
    left_min = [a[0]]
    right_min =[a[last_idx]]

    for i in range(1,last_idx):
        left_min.append(min(a[i],a[i-1]))
        right_min.append(min(a[last_idx-i+1],a[last_idx-i]))
        
    for k in range(1,last_idx-1):
        if max([a[k], left_min[k-1], right_min[last_idx-k]])!=a[k]:
            answer+=1
    print("left_min:",left_min)
    print("right_min:",right_min)
    return answer
                         
solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])                        

left_min: [-16, -16, 27, -2, -2, -92, -92, -71, -68]
right_min: [-33, -61, -68, -71, -92, -92, -2, -2, 27]


4

array([1, 3])

In [85]:
def solution(a):
    answer = 2
    for i in d
    
    return answer

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3

### a[index_i]를 매번 하지않고, 변수하나에 할당했더니 조금 줄어들었다

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.95ms, 27.6MB)
# 테스트 2 〉	통과 (1.94ms, 27.2MB)
# 테스트 3 〉	통과 (0.41ms, 27.9MB)
# 테스트 4 〉	통과 (34.16ms, 31.5MB)
# 테스트 5 〉	통과 (174.47ms, 50MB)
# 테스트 6 〉	통과 (268.11ms, 62.1MB)
# 테스트 7 〉	통과 (339.13ms, 73.3MB)
# 테스트 8 〉	통과 (369.98ms, 73.7MB)
# 테스트 9 〉	통과 (418.99ms, 73.4MB)
# 테스트 10 〉	통과 (1170.56ms, 73.5MB)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)
# 채점 결과

In [73]:
import numpy as np

def solution(a):
    answer = 2
    index_i =0
    
    a = np.array(a)
    min_a = np.min(a[1:])
    min_idx = a.argmin()
    
    min_right_a = min_a
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        num_i = a[index_i]
        if (min_right_a<num_i)&(min_left_a<num_i):
            continue
        else:
            answer+=1
            if min_idx>index_i:
                min_right_a = min_a
                if min_left_a>num_i:
                    min_left_a = num_i
            elif min_idx<=index_i:
                min_left_a = min_a
                if min_right_a==num_i:
                    min_right_a = np.min(a[index_i+1:])

    return answer

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3

### min을 np.min으로 바꿔서 넣었더니 시간이 엄청 줄어들었다???

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (1.29ms, 27.5MB)
# 테스트 2 〉	통과 (0.36ms, 27.5MB)
# 테스트 3 〉	통과 (2.02ms, 27.9MB)
# 테스트 4 〉	통과 (47.17ms, 32.2MB)
# 테스트 5 〉	통과 (226.85ms, 50.2MB)
# 테스트 6 〉	통과 (346.35ms, 62.1MB)
# 테스트 7 〉	통과 (489.51ms, 73.4MB)
# 테스트 8 〉	통과 (474.93ms, 73.6MB)
# 테스트 9 〉	통과 (571.62ms, 73.3MB)
# 테스트 10 〉	통과 (1316.73ms, 73.6MB)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [70]:
def solution(a):
    answer = 2
    index_i =0
    
    a = np.array(a)
    min_a = np.min(a[1:])
    min_idx = a.argmin()
    
    min_right_a = min_a
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            continue
        else:
            answer+=1
            if min_idx>index_i:
                min_right_a = min_a
                if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
            elif min_idx<=index_i:
                min_left_a = min_a
                if min_right_a==a[index_i]:
                    min_right_a = np.min(a[index_i+1:])

    return answer

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3

min 값을 구하는것을 pass처리하고 시간을 구했더니, 300초 대로 모두 떨어졌다. 

min 값을 구하는게 시간 초과의 원인이다

In [204]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.3MB)
# 테스트 2 〉	통과 (0.01ms, 10.3MB)
# 테스트 3 〉	실패 (0.42ms, 10.2MB)
# 테스트 4 〉	실패 (41.91ms, 15.3MB)
# 테스트 5 〉	실패 (212.28ms, 36.9MB)
# 테스트 6 〉	실패 (274.93ms, 50.5MB)
# 테스트 7 〉	실패 (396.11ms, 63.9MB)
# 테스트 8 〉	실패 (339.56ms, 63.8MB)
# 테스트 9 〉	실패 (362.16ms, 63.9MB)
# 테스트 10 〉	실패 (384.12ms, 63.9MB)
# 테스트 11 〉	실패 (366.79ms, 64MB)
# 테스트 12 〉	실패 (350.38ms, 63.9MB)
# 테스트 13 〉	실패 (329.59ms, 63.9MB)
# 테스트 14 〉	실패 (362.90ms, 63.8MB)
# 테스트 15 〉	실패 (367.82ms, 63.9MB)

[5 6 7 8 9 0 3 4 2 1]
True


In [48]:
def solution(a):
    answer = [a[0], a[-1]]
    index_i =0
    
    min1_a = min(a) # 전역 최소값
    min1_a_idx = a.index(min1_a) # 전역최소값 idx
    
    a2 = a.copy()
    a2.remove(min1_a) # 전역 두번째 최소값을 구하기위해 remove
    min2_a = min(a2) # 전역 두번째 최소값
    min2_a_idx = a.index(min2_a) # 전역 두번째 최소값 idx
    
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]) or (min1_a-a[index_i])*(min2_a-a[index_i])<0:
            continue
        else:
            answer.append(a[index_i])
            if min1_a_idx>index_i:
                min_right_a = min1_a
                if min_left_a>=a[index_i]:
                    pass
#                     min_left_a = a[index_i]
            elif min1_a_idx<=index_i:
                min_left_a = min1_a
                if min_right_a>=a[index_i]:
                    pass
#                     min_right_a = min(a[index_i+1:])

    return len(answer)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

3

최소값을 1,2위까지 만들어서 그 사이에 있는것은 pass하도록 예외처리했는데,

시간이 줄지 않고, 오히려 늘어났다

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.3MB)
# 테스트 2 〉	통과 (0.01ms, 10.2MB)
# 테스트 3 〉	통과 (0.50ms, 10.2MB)
# 테스트 4 〉	통과 (28.31ms, 15.3MB)
# 테스트 5 〉	통과 (149.41ms, 36.7MB)
# 테스트 6 〉	통과 (227.07ms, 50.5MB)
# 테스트 7 〉	통과 (306.32ms, 63.9MB)
# 테스트 8 〉	통과 (1047.05ms, 63.9MB)
# 테스트 9 〉	통과 (3318.31ms, 64MB)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [46]:
def solution(a):
    answer = [a[0], a[-1]]
    index_i =0
    
    min1_a = min(a) # 전역 최소값
    min1_a_idx = a.index(min1_a) # 전역최소값 idx
    
    a2 = a.copy()
    a2.remove(min1_a) # 전역 두번째 최소값을 구하기위해 remove
    min2_a = min(a2) # 전역 두번째 최소값
    min2_a_idx = a.index(min2_a) # 전역 두번째 최소값 idx
    
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]) or (min1_a-a[index_i])*(min2_a-a[index_i])<0:
            continue
        else:
            answer.append(a[index_i])
            if min1_a_idx>index_i:
                min_right_a = min1_a
                if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
            elif min1_a_idx<=index_i:
                min_left_a = min1_a
                if min_right_a>=a[index_i]:
                    min_right_a = min(a[index_i+1:])

    return len(answer)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

6

최소값의 유무를 분리해서 예외처리하게 해보았다 -> 빨라졌지만, 그래도 여전히 시간초과

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.2MB)
# 테스트 2 〉	통과 (0.01ms, 10.3MB)
# 테스트 3 〉	통과 (0.51ms, 10.3MB)
# 테스트 4 〉	통과 (25.53ms, 14.5MB)
# 테스트 5 〉	통과 (128.66ms, 33MB)
# 테스트 6 〉	통과 (210.03ms, 44.7MB)
# 테스트 7 〉	통과 (260.98ms, 56.1MB)
# 테스트 8 〉	통과 (1016.58ms, 56.2MB)
# 테스트 9 〉	통과 (3147.11ms, 56.2MB)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	
# 테스트 15 〉	

In [38]:
def solution(a):
    answer = [a[0], a[-1]]
    index_i =0
    min_a = min(a)
    min_idx = a.index(min(a))
    
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            continue
        else:
            answer.append(a[index_i])
            if min_idx>index_i:
                min_right_a = min_a
                if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
            elif min_idx<=index_i:
                min_left_a = min_a
                if min_right_a>=a[index_i]:
                    min_right_a = min(a[index_i+1:])

    return len(answer)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

6

In [ ]:
# 정확성  테스트
# 테스트 1 〉	실패 (0.55ms, 27.9MB)
# 테스트 2 〉	통과 (0.63ms, 28MB)
# 테스트 3 〉	통과 (861.31ms, 28.4MB)
# 테스트 4 〉	실패 (시간 초과)
# 테스트 5 〉	실패 (시간 초과)
# 테스트 6 〉	실패 (시간 초과)
# 테스트 7 〉	실패 (시간 초과)
# 테스트 8 〉	실패 (시간 초과)
# 테스트 9 〉	실패 (시간 초과)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [18]:
import numpy as np

def solution(a):
    answer = 2 #처음(a[0]), 끝(a[-1])
    argsort_a = np.argsort(a)
    
    for i in range(2,len(argsort_a)):
        smaller_than_i = argsort_a[1:i]
        if sum(smaller_than_i<argsort_a[i])in [0, len(smaller_than_i)]:
            answer+=1
    return answer

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3

In [17]:
import numpy as np

def solution(a):
    answer = 2 #처음(a[0]), 끝(a[-1])
    argsort_a = np.argsort(a)
    print(argsort_a)
    
    for i in range(2,len(argsort_a)):
        smaller_than_i = argsort_a[1:i]
        print(smaller_than_i)
        if sum(smaller_than_i<argsort_a[i])in [0, len(smaller_than_i)]:
            answer+=1
        print(smaller_than_i<argsort_a[i])
        print(sum(smaller_than_i<argsort_a[i]))
    return answer

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

[2 1 0]
[1]
[False]
0


3

### 도저히 시간을 줄일수가 없음!

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.04ms, 27.7MB)
# 테스트 2 〉	통과 (0.05ms, 27.8MB)
# 테스트 3 〉	통과 (1.53ms, 27.8MB)
# 테스트 4 〉	통과 (126.25ms, 32.8MB)
# 테스트 5 〉	통과 (605.52ms, 54.5MB)
# 테스트 6 〉	통과 (947.32ms, 67.8MB)
# 테스트 7 〉	통과 (1223.70ms, 81.3MB)
# 테스트 8 〉	통과 (2061.25ms, 81.5MB)
# 테스트 9 〉	통과 (4132.10ms, 81.1MB)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [193]:
def solution(a):
    answer = [a[0], a[-1]]
    min_idx_1 = np.argsort(a)[0]
    min_idx_2 = np.argsort(a)[1]
    
    index_i =0
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_idx_1-index_i)*(min_idx_2-index_i)<0 or (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            continue
        else:
            answer.append(a[index_i])
            if min_right_a>=a[index_i]:
                min_right_a = min(a[index_i+1:])
            if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
    return len(answer)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

6

### 예외처리
- 최소값 1,2등 사이에 있다면 빼주자

- -> 시간이 늘어나기만 하고 이점이 없다!
- -> 그 말은 pass되는 것을 처리하는 것은 더이상 무의미

In [150]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.2MB)
# 테스트 2 〉	통과 (0.01ms, 10.3MB)
# 테스트 3 〉	통과 (0.52ms, 10.2MB)
# 테스트 4 〉	통과 (30.60ms, 15.2MB)
# 테스트 5 〉	통과 (161.94ms, 36.8MB)
# 테스트 6 〉	통과 (254.77ms, 50.3MB)
# 테스트 7 〉	통과 (325.79ms, 63.9MB)
# 테스트 8 〉	통과 (1138.21ms, 63.9MB)
# 테스트 9 〉	통과 (3297.36ms, 63.9MB)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

2

In [175]:
def solution(a):
    answer = [a[0], a[-1]]
    min1_a = min(a) # 전역 최소값
    min1_a_idx = a.index(min1_a) # 전역최소값 idx
    
    a2 = a.copy()
    a2.remove(min1_a) # 전역 두번째 최소값을 구하기위해 remove
    min2_a = min(a2) # 전역 두번째 최소값
    min2_a_idx = a.index(min2_a) # 전역 두번째 최소값 idx
    
    index_i =0
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min1_a_idx-index_i)*(min2_a_idx-index_i)<0 or (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            continue
        else:
            answer.append(a[index_i])
            if min_right_a>=a[index_i]:
                min_right_a = min(a[index_i+1:])
            if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
    return len(answer)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

6

### 넘파이의 argsort를 이용해서 메모리를 줄일 수있을까?

In [190]:
# a = [9,-1,-5] #3
a = [-16,27,65,-2,58,-92,-71,-68,-61,-33]  #6 - 16, -92, -71, -68, -61, -33

answer = []
a = np.array(a)
# print(a)
min1 = np.argsort(a)[0]
min2 = np.argsort(a)[1]

print("min1: ",min1)
print("min2: ",min2)

min1:  5
min2:  6


In [183]:
np.where(b==0) #최소값
min2_idx = np.where(b==1)[0][0] #두번째 최소값
a[min2_idx]

-68

In [192]:
def solution(a):
    answer = 2
    
    index_i =0
    min_idx_1 = np.argsort(a)[0]
    min_idx_2 = np.argsort(a)[1]
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_idx_2-index_i)*(min_idx_1-index_i)<0:
            continue
        elif (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            continue
        else:
            answer+=1
            if (min_idx_1<=index_i)&(min_right_a>=a[index_i]):
                min_right_a = min(a[index_i+1:])
            if (min_idx_1>=index_i)&(min_left_a>=a[index_i]):
                min_left_a = a[index_i]
    return answer

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

6

### 시간초과를 없애기 위한 예외처리
--> 크게 줄지 않음...

1)  최소값이 right에 남아있으면, 굳이 최소값 구할필요 없다

2)  최소값이 left에 이미 넘어왔으면, 굳이 최소값 구할필요 없다.

In [113]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.2MB)
# 테스트 2 〉	통과 (0.01ms, 10.2MB)
# 테스트 3 〉	통과 (0.44ms, 10.2MB)
# 테스트 4 〉	통과 (24.68ms, 14.5MB)
# 테스트 5 〉	통과 (120.07ms, 32.9MB)
# 테스트 6 〉	통과 (198.45ms, 44.8MB)
# 테스트 7 〉	통과 (247.39ms, 56.2MB)
# 테스트 8 〉	통과 (1021.00ms, 56.1MB)
# 테스트 9 〉	통과 (3220.88ms, 56.1MB)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [114]:
def solution(a):
    answer = [a[0], a[-1]]
    index_i =0
    min_idx = a.index(min(a))
    
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            pass
        else:
            answer.append(a[index_i])
            if (min_idx<=index_i)&(min_right_a>=a[index_i]):
                min_right_a = min(a[index_i+1:])
            if (min_idx>=index_i)&(min_left_a>=a[index_i]):
                min_left_a = a[index_i]
    return len(answer)

# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3

### 기존 a.remove 방식에서, answer.append로 바꿈

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.2MB)
# 테스트 2 〉	통과 (0.01ms, 10.3MB)
# 테스트 3 〉	통과 (0.41ms, 10.2MB)
# 테스트 4 〉	통과 (20.78ms, 14.4MB)
# 테스트 5 〉	통과 (106.58ms, 33MB)
# 테스트 6 〉	통과 (179.14ms, 44.7MB)
# 테스트 7 〉	통과 (208.20ms, 56.3MB)
# 테스트 8 〉	통과 (998.48ms, 56.2MB)
# 테스트 9 〉	통과 (3302.76ms, 56.1MB)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [101]:
def solution(a):
    answer = [a[0], a[-1],min]
    index_i =0
    min_right_a = min(a[1:])
    min_left_a = a[0]
    
    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            pass
        else:
            answer.append(a[index_i])
            if min_right_a>=a[index_i]:
                min_right_a = min(a[index_i+1:])
            if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
    return len(answer)

3

### 원포인트 스왑
-  겨우 한문제더 맞춤....

In [ ]:
# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.2MB)
# 테스트 2 〉	통과 (0.01ms, 10.2MB)
# 테스트 3 〉	통과 (0.72ms, 10.2MB)
# 테스트 4 〉	통과 (707.26ms, 15.3MB)
# 테스트 5 〉	실패 (시간 초과)
# 테스트 6 〉	실패 (시간 초과)
# 테스트 7 〉	실패 (시간 초과)
# 테스트 8 〉	실패 (시간 초과)
# 테스트 9 〉	실패 (시간 초과)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [59]:
def solution(a):
    b = a.copy()

    index_i =0
    min_right_a = min(a[1:])
    min_left_a = a[0]

    while index_i<(len(a)-2):
        index_i+=1
        if (min_right_a<a[index_i])&(min_left_a<a[index_i]):
            b.remove(a[index_i])
        else:
            if min_right_a>=a[index_i]:
                min_right_a = min(a[index_i+1:])
            if min_left_a>=a[index_i]:
                    min_left_a = a[index_i]
    return len(b)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
# solution([9,-1,-5])

6

In [35]:
a = [9,-1,-5] #3
a = [-16,27,65,-2,58,-92,-71,-68,-61,-33]  #6 - 16, -92, -71, -68, -61, -33
b = a.copy()

index_i =0
min_right_a = min(a[1:])
min_left_a = a[0]

while index_i<(len(a)-2):
    index_i+=1
    print(index_i)
    print("i번째수:",a[index_i])
    print("min_right_a: ",min_right_a)
    print("min_left_a: ",min_left_a)
    if (min_right_a<a[index_i])&(min_left_a<a[index_i]):
        b.remove(a[index_i])
        print("지금 remove")
    else:
        if min_right_a>=a[index_i]:
            min_right_a = min(a[index_i+1:])
        if min_left_a>=a[index_i]:
                min_left_a = a[index_i]
print(b)  

1
i번째수: 27
min_right_a:  -92
min_left_a:  -16
지금 remove
2
i번째수: 65
min_right_a:  -92
min_left_a:  -16
지금 remove
3
i번째수: -2
min_right_a:  -92
min_left_a:  -16
지금 remove
4
i번째수: 58
min_right_a:  -92
min_left_a:  -16
지금 remove
5
i번째수: -92
min_right_a:  -92
min_left_a:  -16
6
i번째수: -71
min_right_a:  -71
min_left_a:  -92
7
i번째수: -68
min_right_a:  -68
min_left_a:  -92
8
i번째수: -61
min_right_a:  -61
min_left_a:  -92
[-16, -92, -71, -68, -61, -33]


In [25]:
#### 엄청난 시간초과.. 

# 정확성  테스트
# 테스트 1 〉	통과 (0.01ms, 10.2MB)
# 테스트 2 〉	통과 (0.01ms, 10.1MB)
# 테스트 3 〉	통과 (20.97ms, 10.3MB)
# 테스트 4 〉	실패 (시간 초과)
# 테스트 5 〉	실패 (시간 초과)
# 테스트 6 〉	실패 (시간 초과)
# 테스트 7 〉	실패 (시간 초과)
# 테스트 8 〉	실패 (시간 초과)
# 테스트 9 〉	실패 (시간 초과)
# 테스트 10 〉	실패 (시간 초과)
# 테스트 11 〉	실패 (시간 초과)
# 테스트 12 〉	실패 (시간 초과)
# 테스트 13 〉	실패 (시간 초과)
# 테스트 14 〉	실패 (시간 초과)
# 테스트 15 〉	실패 (시간 초과)

In [42]:
b = a.copy()
for i in range(1,len(a)):
    try:
        before_min = min(a[:i])
    except:
        before_min = max(a)+1
    try:
        after_min = min(a[i+1:])
    except:
        after_min = max(a)+1
    if (before_min<a[i])&(after_min<a[i]):
        b.remove(a[i])

print(b)   

[-16, -92, -71, -68, -61, -33]


In [32]:
def solution(a):
    b = a.copy()
    
    for i in range(1,len(a)):
        try:
            before_min = min(a[:i])
        except:
            before_min = max(a)+1
    
        try:
            after_min = min(a[i+1:])
        except:
            after_min = max(a)+1
        
        if (before_min<a[i])&(after_min<a[i]):
            b.remove(a[i])
    return len(b)

solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3

In [157]:
def solution(a):
    
    if len(a) < 3:
        return 2
    else:
        answer = 2
        for i in range(1,len(a)-1):
            output = 1



            min_left = min(a[:i])
            min_right = min(a[i+1:])
            num = a[i]



            if min_left> num:
                output *= 0
            else:
                output *= 1

            if min_right > num:
                output *= 0
            else:
                output *= 1


            if output != 1:
                answer += 1
        return answer
    
# solution([-16,27,65,-2,58,-92,-71,-68,-61,-33])
solution([9,-1,-5])

3