#### 문제 설명
- 고고학자인 튜브는 고대 유적지에서 보물과 유적이 가득할 것으로 추정되는 비밀의 문을 발견하였습니다. 그런데 문을 열려고 살펴보니 특이한 형태의 자물쇠로 잠겨 있었고 문 앞에는 특이한 형태의 열쇠와 함께 자물쇠를 푸는 방법에 대해 다음과 같이 설명해 주는 종이가 발견되었습니다.

- 잠겨있는 자물쇠는 격자 한 칸의 크기가 1 x 1인 N x N 크기의 정사각 격자 형태이고 특이한 모양의 열쇠는 M x M 크기인 정사각 격자 형태로 되어 있습니다.

- 자물쇠에는 홈이 파여 있고 열쇠 또한 홈과 돌기 부분이 있습니다. 열쇠는 회전과 이동이 가능하며 열쇠의 돌기 부분을 자물쇠의 홈 부분에 딱 맞게 채우면 자물쇠가 열리게 되는 구조입니다. 자물쇠 영역을 벗어난 부분에 있는 열쇠의 홈과 돌기는 자물쇠를 여는 데 영향을 주지 않지만, 자물쇠 영역 내에서는 열쇠의 돌기 부분과 자물쇠의 홈 부분이 정확히 일치해야 하며 열쇠의 돌기와 자물쇠의 돌기가 만나서는 안됩니다. 또한 자물쇠의 모든 홈을 채워 비어있는 곳이 없어야 자물쇠를 열 수 있습니다.

- 열쇠를 나타내는 2차원 배열 key와 자물쇠를 나타내는 2차원 배열 lock이 매개변수로 주어질 때, 열쇠로 자물쇠를 열수 있으면 true를, 열 수 없으면 false를 return 하도록 solution 함수를 완성해주세요.

#### 제한사항
- key는 M x M(3 ≤ M ≤ 20, M은 자연수)크기 2차원 배열입니다.
- lock은 N x N(3 ≤ N ≤ 20, N은 자연수)크기 2차원 배열입니다.
- M은 항상 N 이하입니다.
- key와 lock의 원소는 0 또는 1로 이루어져 있습니다.
- 0은 홈 부분, 1은 돌기 부분을 나타냅니다.


In [258]:
key = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 1]])
lock = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 1]])

import  numpy as np

def rotate_90(input_array):
    n = len(input_array)
    output_array = np.zeros_like(input_array)
    for i in range(n):
        for k in range(n):
            output_array[k][n-1-i] = input_array[i][k]
    return output_array


def get_pure_out(input_array):
    n = len(input_array)
    
    col_start = np.where(input_array.sum(0)!=0)[0]
    if col_start.size>0:
        col_start = col_start[0]
    else: col_start = 0
    row_start = np.where(input_array.sum(1)!=0)[0]
    if row_start.size>0:
        row_start = row_start[0]
    else: row_start = 0

    col_end = np.where(input_array.sum(0)!=0)[0]
    if col_end.size>0:
        col_end = col_end[-1]
    else: col_end = n-1 
    row_end = np.where(input_array.sum(1)!=0)[0]
    if row_end.size>0:
        row_end = row_end[-1]
    else: row_end = n-1
    return input_array[row_start:row_end+1, col_start:col_end+1]


def get_pure_in(input_array):
    n = len(input_array)
    
    col_start = np.where(input_array.sum(0)==0)[0]
    if col_start.size>0:
        col_start = col_start[0]
    else: col_start = 0
    row_start = np.where(input_array.sum(1)==0)[0]
    if row_start.size>0:
        row_start = row_start[0]
    else: row_start = 0

    col_end = np.where(input_array.sum(0)==0)[0]
    if col_end.size>0:
        col_end = col_end[-1]
    else: col_end = n-1 
    row_end = np.where(input_array.sum(1)==0)[0]
    if row_end.size>0:
        row_end = row_end[-1]
    else: row_end = n-1
        
    return input_array[row_start:row_end+1, col_start:col_end+1]

pure_key = get_pure_out(key)
pure_hom = get_pure_in(key)

# if pure_key

In [260]:
pure_hom

array([[0, 0, 0]])

In [261]:
pure_key

array([[1, 0, 0],
       [0, 1, 1]])

In [136]:
key_list[1]

array([[0, 1, 0],
       [1, 0, 0]])

In [253]:
key = [[0, 1,0 ], [1, 1, 0], [0, 0, 0]]
key = np.array(key)
key

array([[0, 1, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [262]:
get_pure_in(key)

array([[0, 0, 0]])

In [240]:
np.where(key.sum(1)==0)[0]

array([], dtype=int64)

In [230]:
get_pure_in(key)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [220]:
get_pure_match(key,1)

array([[1, 0],
       [0, 0]])

In [223]:
num=1
col_start = np.where(key.sum(0)!=num)[0][0]
# row_start = np.where(input_array.sum(1)!=num)[0][0]

# col_end = np.where(input_array.sum(0)!=num)[0][-1]
# row_end = np.where(input_array.sum(1)!=num)[0][-1]

In [193]:
#col_start
np.where(key.sum(0)!=0)[0]


array([0, 1, 2], dtype=int64)

In [172]:
#row_start 
np.where(key.sum(1)!=0)[0][0]

0

In [13]:
lock

array([[1, 1, 1],
       [1, 1, 0],
       [1, 0, 1]])

In [129]:
len(lock)*len(lock)-lock.sum()

2

In [4]:
lock.sum(axis=0)

array([3, 2, 2])

In [9]:
lock.sum(axis=1)

array([3, 2, 2])

In [5]:
### -> TRUE = 통과/FALSE= 실패
# 정확성  테스트
# 테스트 1 〉	실패 (0.00ms, 10.2MB)
# 테스트 2 〉	통과 (0.00ms, 10MB)
# 테스트 3 〉	통과 (0.00ms, 10.2MB)
# 테스트 4 〉	통과 (0.00ms, 10.2MB)
# 테스트 5 〉	통과 (0.00ms, 10.2MB)
# 테스트 6 〉	통과 (0.00ms, 10.2MB)
# 테스트 7 〉	통과 (0.00ms, 10.2MB)
# 테스트 8 〉	통과 (0.00ms, 10.2MB)
# 테스트 9 〉	통과 (0.00ms, 10.1MB)
# 테스트 10 〉	통과 (0.00ms, 10.2MB)
# 테스트 11 〉	통과 (0.00ms, 10.1MB)
# 테스트 12 〉	통과 (0.00ms, 10.1MB)
# 테스트 13 〉	통과 (0.00ms, 10.2MB)
# 테스트 14 〉	통과 (0.00ms, 10.2MB)
# 테스트 15 〉	통과 (0.00ms, 10.1MB)
# 테스트 16 〉	통과 (0.00ms, 10.1MB)
# 테스트 17 〉	통과 (0.00ms, 10.2MB)
# 테스트 18 〉	통과 (0.00ms, 10MB)
# 테스트 19 〉	통과 (0.00ms, 10.2MB)
# 테스트 20 〉	통과 (0.00ms, 10MB)
# 테스트 21 〉	통과 (0.00ms, 10.2MB)
# 테스트 22 〉	통과 (0.00ms, 10.2MB)
# 테스트 23 〉	실패 (0.00ms, 10.2MB)
# 테스트 24 〉	실패 (0.00ms, 10.2MB)
# 테스트 25 〉	실패 (0.00ms, 10.1MB)
# 테스트 26 〉	실패 (0.00ms, 10.3MB)
# 테스트 27 〉	실패 (0.00ms, 10.1MB)
# 테스트 28 〉	실패 (0.00ms, 10.1MB)
# 테스트 29 〉	실패 (0.00ms, 10.2MB)
# 테스트 30 〉	실패 (0.00ms, 10.2MB)
# 테스트 31 〉	실패 (0.00ms, 10.2MB)
# 테스트 32 〉	실패 (0.00ms, 10.1MB)
# 테스트 33 〉	실패 (0.00ms, 10.1MB)
# 테스트 34 〉	통과 (0.00ms, 10.2MB)
# 테스트 35 〉	통과 (0.00ms, 10.2MB)
# 테스트 36 〉	통과 (0.00ms, 10.2MB)
# 테스트 37 〉	통과 (0.00ms, 10.2MB)
# 테스트 38 〉	통과 (0.00ms, 10.2MB)